# Generated by Django 2.2 on 2019-09-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0003_auto_20190912_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award_list',
            options={'verbose_name_plural': 'Award'},
        ),
        migrations.AlterModelOptions(
            name='cast_list',
            options={'verbose_name_plural': 'Cast'},
        ),
        migrations.AlterModelOptions(
            name='country_list',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='director_list',
            options={'verbose_name_plural': 'Director'},
        ),
        migrations.AlterModelOptions(
            name='episode_list',
            options={'verbose_name_plural': 'Episode'},
        ),
        migrations.AlterModelOptions(
            name='genre_list',
            options={'verbose_name_plural': 'Genre'},
        ),
        migrations.AlterModelOptions(
            name='language_list',
            options={'verbose_name_plural': 'Language'},
        ),
        migrations.AlterModelOptions(
            name='link_list',
            options={'verbose_name_plural': 'Link'},
        ),
        migrations.AlterModelOptions(
            name='movies_list',
            options={'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='movies_type_list',
            options={'verbose_name_plural': 'movies_type'},
        ),
        migrations.AlterModelOptions(
            name='quality_list',
            options={'verbose_name_plural': 'Quality'},
        ),
        migrations.AlterModelOptions(
            name='season_list',
            options={'verbose_name_plural': 'Season'},
        ),
        migrations.AlterModelOptions(
            name='server_list',
            options={'verbose_name_plural': 'Server_name'},
        ),
        migrations.AlterModelOptions(
            name='server_type_list',
            options={'verbose_name_plural': 'Server_type'},
        ),
        migrations.AlterModelOptions(
            name='writer_list',
            options={'verbose_name_plural': 'Writer'},
        ),
    ]
