# Generated by Django 2.2 on 2019-09-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0004_auto_20190912_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award_list',
            name='award_image',
            field=models.ImageField(upload_to='award_pics'),
        ),
    ]
