# Generated by Django 2.2 on 2019-09-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0010_auto_20190914_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_list',
            name='link_user_id',
        ),
        migrations.AddField(
            model_name='movies_list',
            name='movie_episode_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies_list',
            name='movies_season_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season_list',
            name='movies_season_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
