# Generated by Django 2.2 on 2019-09-14 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_list', '0011_auto_20190914_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies_list',
            name='movie_episode_id',
        ),
        migrations.RemoveField(
            model_name='movies_list',
            name='movies_season_id',
        ),
        migrations.RemoveField(
            model_name='season_list',
            name='movies_season_id',
        ),
        migrations.AddField(
            model_name='link_list',
            name='link_user_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
