# Generated by Django 2.2 on 2019-09-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0012_auto_20190914_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_list',
            name='ratting',
            field=models.FloatField(default=0.0),
        ),
    ]
