# Generated by Django 2.2 on 2019-09-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0013_auto_20190914_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link_list',
            old_name='server_name',
            new_name='link_episode_season_id',
        ),
    ]
