# Generated by Django 2.2 on 2019-09-14 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0014_auto_20190914_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_list',
            name='link_episode_season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies_list.Episode_list'),
        ),
    ]
