# Generated by Django 2.2 on 2019-09-15 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_list', '0018_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='screenshot',
            field=models.ImageField(blank=True, upload_to='contact_pics'),
        ),
    ]
